mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include('polls.urls')),
    path("", TemplateView.as_view(template_name = "index.html"))
]

polls/urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    path("",views.IndexView.as_view(), name="index"),   
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:q_id>/votes/", views.votes, name="vote"),
    path("meme/",views.meme, name="memes"),
]

polls/models.py
from django.db import models

# Create your models here.

# Модель для обработки вопроса
class Question(models.Model):
    text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    # В момент конвертации в str() 
    def __str__(self):
        return self.text


# Модель для обработки варианта ответа на вопрос
class Choice(models.Model):
    # Связываем Quetions и Choices
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    votes = models.IntegerField(default=0)
    # В момент конвертации в str() 
    def __str__(self):
        return self.text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic 

from .models import Question, Choice 


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "questions"

    def get_queryset(self):
        return Question.objects.all()

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"



def votes(request, q_id):
    choices = request.POST.getlist("choice")
    question = Question.objects.get(pk= q_id)
    res =   ""
    for c_pk in choices:
        choice = question.choice_set.get(pk=c_pk)
        choice.votes += 1
        choice.save()
      
    return HttpResponseRedirect( reverse("polls:results", args=(q_id, )) )
      
def results(request, q_id):    
    question = Question.objects.get(pk= q_id)

    context = {
        "question" : question,       
    }

    return render(request, "polls/results.html", context)











def meme(request):
    return HttpResponse('<img src = https://upload.wikimedia.org/wikipedia/ru/4/4d/Wojak.png    ></img>')

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>{{question.text}}</h1>
    {% if question.choice_set.all %}
    <form method="POST" action="{% url 'polls:vote' question.pk %}">
        {% csrf_token %}
        {%for c in question.choice_set.all%}
        <input type="checkbox" name="choice" id="c{{c.pk}}" value="{{c.pk}}"> <label for ="c{{c.pk}}">{{c.text}}</label> 
        <br>
        {%endfor%}

        <button type="submit">Vote</button> 
    </form>
    {% endif %}
    
    
    
    
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if questions  %}
    <ol>
        {% for q in questions  %}
        <li> <a href="/polls/{{q.pk}}/">{{q.text}}</a> </li>
        {% endfor %}
    </ol>
    
    {% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{question.text}}</h1>
    {% if question.choice_set.all %}
        <ul>
        {% for c in question.choice_set.all  %}
            <li>{{c.text}}: {{c.votes}}</li>
        {% endfor %}
        </ul>
    {% endif %}


    <a href="{% url 'polls:index' %}">Вернуться назад</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="css/index.css">
    <title>Document</title>
    <style>
        body {
            background-color:rgb(128, 216, 238);
        }
        h1 {
            text-align: center;
            margin-top: 15px;
        }
        img {
            width: 100px;
            height: 100px;
            margin-top: 15px;
            margin-left: 47.6%;
        }
        button {
            margin-left: 48.7%;
            
        }
    </style>
</head>
<body>


    <h1>HAAI</h1>  
    <a href=" {% url 'polls:index' %}"><button>Start</button></a>
    <br>
    <img src="https://sun9-74.userapi.com/impg/Nyem0jCujfqyAzFWuffh54guhXL2nsqjAO7y2Q/jP9ik-T7sVA.jpg?size=555x554&quality=96&sign=060dbb8a414f52c5d23538cf3a77d1a4&type=album" alt="">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>